server:
  port: 8080
  servlet:
    context-path: /yolp

spring:
  application:
    name: yolp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=invincible
    username: postgres
    password: revature
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop


